version: 2
jobs:
   build:
     docker:
       - image: ubuntu:16.04 
     working_directory: ~/LossyCountingModel
     steps:
       - run: apt update && apt install git build-essential --yes
       - checkout
       - run: make -C test
       - run: ./test/lcm_test
